version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-fakeapicc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6bdglq8o5ko5"
s3_prefix = "sam-fakeapicc"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RunEnvironment=\"prod\""
