AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fakeapi.cc

  Sample SAM Template for fakeapi.cc
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  fakeapi-get:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: fakeapi-get/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        FakeApi-CC:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /person
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FakeApi-CC:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/person/"
  fakeapi-get:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt fakeapi-get.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for fakeapi-get function"
    Value: !GetAtt fakeapi-get-role.Arn
